# Generated by Django 4.2 on 2023-07-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_customuser_is_institute_customuser_is_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
