# Generated by Django 4.2 on 2023-07-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0003_customuser_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='class_name',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='division',
            field=models.CharField(choices=[('Azalea', 'Azalea'), ('Zinnia', 'Zinnia'), ('Camelia', 'Camelia')], max_length=10, null=True),
        ),
    ]
