# Generated by Django 4.2 on 2023-07-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0004_alter_customuser_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
