# Generated by Django 4.2 on 2023-07-14 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0010_remove_useranswer_options_useranswer_selected_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.exam'),
        ),
    ]
