# Generated by Django 4.2 on 2023-07-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0011_useranswer_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=200),
        ),
    ]
