# Generated by Django 4.2 on 2023-07-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0013_alter_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='staff_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
