# Generated by Django 4.2 on 2023-07-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0014_exam_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_time',
            field=models.TimeField(null=True),
        ),
    ]
