# Generated by Django 4.2 on 2023-07-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0017_alter_customuser_student_prn_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_prn_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
