# Generated by Django 4.2 on 2023-07-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0020_exam_designation_exam_email_exam_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='email',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
