# Generated by Django 4.2 on 2023-07-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0021_remove_exam_designation_remove_exam_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
    ]
