# Generated by Django 4.2 on 2023-07-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0022_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
    ]
