# Generated by Django 4.2 on 2023-07-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0023_class_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class_Names',
        ),
    ]
