# Generated by Django 4.2 on 2023-07-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0024_delete_class_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='record_created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
